"""
Email Sender
============
Sends the generated newsletter via Gmail SMTP.
Uses environment variables for secure credential handling.
"""

import smtplib
import os
import ssl
from email.message import EmailMessage
from dotenv import load_dotenv

load_dotenv()

# Placeholder images for email header/footer
# You can replace these with your own hosted images
HEADER_IMG = "https://placehold.co/600x100/1a1a1a/ffffff/png?text=The+Weekly+Sync&font=lora"
FOOTER_IMG = "https://placehold.co/600x50/f4f4f4/888888/png?text=Generated+by+Your+AI+Agent"


def send_email(html_content, subject="🚀 The Weekly Sync"):
    """
    Sends an HTML email with the newsletter content.
    Supports multiple recipients - separate emails with commas.
    
    Args:
        html_content: The HTML body content (generated by LLM)
        subject: Email subject line
        
    Returns:
        True if sent successfully, False otherwise
    """
    # Get credentials from environment
    sender_email = os.environ.get("EMAIL_ADDRESS")
    print("    DEBUG sender:", sender_email)
    password = os.environ.get("EMAIL_APP_PASSWORD")
    recipient_env = os.environ.get("RECIPIENT_EMAIL")
    RECIPIENT_EMAIL="alex.s.pennington@outlook.com"
    
    # Support multiple recipients (comma-separated)
    recipients = [email.strip() for email in recipient_env.split(",") if email.strip()]
    print("    DEBUG recipients:", recipients)

    # Validate credentials
    if not sender_email or not password:
        print("    ❌ Error: Missing EMAIL_ADDRESS or EMAIL_APP_PASSWORD in .env file.")
        print("    → See README.md for setup instructions.")
        return False
    
    if not recipients:
        print("    ❌ Error: Missing RECIPIENT_EMAIL in .env file.")
        return False

    # Build the email
    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = sender_email
    msg['To'] = ", ".join(recipients)  # Multiple recipients supported

    # Wrap AI content in a beautiful template
    full_html = _build_email_template(html_content)
    #msg.add_alternative(full_html, subtype='html')
    msg.set_content("Test email from newsletter script.")

    # Send via Gmail SMTP
    try:
        recipient_display = ", ".join(recipients) if len(recipients) <= 3 else f"{len(recipients)} recipients"
        print(f"    📤 Sending to {recipient_display}...")
        context = ssl.create_default_context()

        with smtplib.SMTP('smtp.gmail.com', 587) as smtp:
            smtp.starttls(context=context)
            smtp.login(sender_email, password)
            smtp.send_message(msg)
            
        print("    ✅ Email sent successfully!")
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("    ❌ Authentication failed. Check your email/app password.")
        print("    → Make sure you're using an App Password, not your regular password.")
        print("    → See: https://support.google.com/accounts/answer/185833")
        return False
        
    except smtplib.SMTPRecipientsRefused:
        print(f"    ❌ Recipient refused: {receiver_email}")
        return False
        
    except Exception as e:
        print(f"    🔥 Email failed: {e}")
        return False


def _build_email_template(content):
    """
    Wraps the AI-generated content in a beautiful FT-style email template.
    """
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
    <style>
        body {{ font-family: 'Georgia', serif; background-color: #f4f4f4; margin: 0; padding: 0; }}
        .container {{ max-width: 600px; margin: 20px auto; background: #ffffff; padding: 0; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
        .header {{ width: 100%; text-align: center; background-color: #1a1a1a; }}
        .header img {{ max-width: 100%; height: auto; display: block; }}
        .content {{ padding: 30px; color: #333333; line-height: 1.6; }}
        .footer {{ padding: 20px; text-align: center; font-size: 12px; color: #888; background-color: #f4f4f4; }}
        
        /* Typography */
        h2 {{ color: #990000; border-bottom: 2px solid #ddd; padding-bottom: 10px; margin-top: 30px; font-size: 22px; }}
        h3 {{ color: #1a1a1a; margin-bottom: 5px; font-size: 18px; margin-top: 25px; }}
        a {{ color: #990000; text-decoration: none; font-weight: bold; }}
        a:hover {{ text-decoration: underline; }}
    </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <img src="{HEADER_IMG}" alt="The Weekly Sync">
            </div>

            <div class="content">
                {content}
            </div>

            <div class="footer">
                <img src="{FOOTER_IMG}" alt="Footer"><br><br>
                Automated Briefing | Generated by Gemini 2.0
            </div>
        </div>
    </body>
    </html>
    """
